### ISSUE TITLE
Org membership request

### ISSUE THREAD

**Issue by gordonfarrell** [CDCgov/template#116]
**What type of help do you need?**

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [X] User Membership (please make sure new members are familiar with the [CDC open practices](https://github.com/CDCgov/template/blob/master/open_practices.md#profile-setup) and set up their profile with name and org info to help people collaborate with them)
* [ ] Other

**Please describe how you'd like us to help.**

Hello! I'm Gordon Farrell, a CDC/IOD/OPHDST contractor with Skylight and Tech Lead for the DIBBs Streamline eCR team (in the confusingly named [PHDI repo](https://github.com/CDCgov/phdi)). I was hoping to become an org member with the ability to create and assign teams in order to set up code owner groups for auto PR review requests.

Please let me know if you need any additional information from me. Thank you!

**Comment by boris-ning-usds** [comment]
Hi Gordan,

Becoming an org member can come with a lot more responsibility than the ability to create and assign teams; based on the [organizational roles](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization) provided by Github, an org owner, for example, has to onboard/offboard users, triage issues with users (ex. workflows, etc) and handle administrative problems and integrations of Github.

With that said, there are couple ways we can go about this.
1. Provide you with a Github app with limited scope (ex. create teams) such that your team controls so that you can [terraform the Github organization](https://registry.terraform.io/providers/integrations/github/latest/docs) with particular teams and members that you need. This is preferred because this Github app can live on as a managed identity for automation - not bounded to a single user. I've done this within another [CDC Github organization](https://github.com/cdcent/ocio-github-infra/tree/main/terraform).
2. Onboard you to cdcgov and make you a moderator. Based on Github [organizational roles](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization), it looks like a moderator role provide you with the ability to create teams but it'll require some testing.

**Comment by boris-ning-usds** [comment]
Onboarded Gordon (ukr7) as user, and added as moderator so that he can create teams.
Had a chat with him on how to handle situations.

Calling this issue completed.
