### ISSUE TITLE
Add support for external static analysis and code quality tools

### ISSUE THREAD

**Issue by nickrobison-usds** [CDCgov/template#12]
Add support for common code quality and static analysis tools to integrate with CDCGov repos.

* [ ] Question
* [ ] New Repo
* [ ] Delete Repo
* [x] Other

As part of our security review process for the Prime applications, we'd like to add support for running automated code quality and security analysis checks as part of our normal PR review process.

As this is a pretty common process for open source projects, there are a lot of really solid options out there that are well tested and widely used across industry and government. Specifically, there are a couple that we (USDS) has used successfully in other federal agencies. As an example, see the [Data at the Point of Care](https://github.com/CMSgov/dpc-app) project from CMS, which is a high profile project that deals with large amounts of PII.

From the perspective of their security office and our own development teams, the value of having automated tooling that performs both deep analysis of code flow and execution as well as more high level checks such as test coverage and consistent styling significantly outweighed the potential risks of integrating with third party tooling.

A couple of high level points on this: 
- The analysis applications DO NOT have the ability to modify code or merge changes into the repositories. Some only require read-only access to the repository, while some support the ability to automatically comment on Pull Requests to help pinpoint and resolve errors quickly.
- No secrets are stored on the third party servers, they simple work with what is publicly available in the repository.
- No connection is required to other CDC resources
- The applications operate in an advisory mode, which means that if the services are unavailable or shutdown, development proceeds normally with no impact to security or development velocity.

With that in mind, we're requesting the following services be enabled for CDC repositories:

## [SonarCloud](sonarcloud.io)
This application provides comprehensive code quality management over the course of an application's lifetime. It's the SAAS version of SonarQube, which means it doesn't require installation or maintenance on our part. The value of this application is that it provides an integrated environment for monitoring code quality, test coverage and style consistency. The application only requires read access to the code, but but does have support for commenting on Pull Requests and providing pass/fail checks.

### Documentation links:
- https://sonarcloud.io/documentation/appendices/security/
- https://sonarcloud.io/documentation/integrations/github/
- https://sonarcloud.io/documentation/appendices/privacy/

## [Coverity](scan.coverity.com)
Coverity is a proprietary static and dynamic analysis application for a number of different programming languages. It provides free usage for open source projects and is leveraged by project such as the Linux kernel. It normally runs as part of the CI process and requires manual resolution of issues and alerts. This means it only needs read access to the code and runs asynchronously from the normal development workflow. While this tool is propriety it provides a level of control flow and branch analysis insight that's hard to replicate with other tools.

### Documentation links:
- https://scan.coverity.com/projects
- https://scan.coverity.com/about
- https://scan.coverity.com/policy
- https://scan.coverity.com/faq

##  Repos
To begin with, we'd like to enable access to the following repos, with potentially more to come at a later date:

- https://github.com/CDCgov/prime-data-input-client
- https://github.com/CDCgov/prime-data-hub

Happy to provide any additional insight or documentation as needed.

**Comment by leebrian** [comment]
Thanks so much Nick, this info is really helpful. I think these are all useful and appropriate third party plugins and apps and will grant access. While I haven't used these services, they appear safe because they are not changing any project code and any changes to issues and pull requests can be monitored and configured by project admins.

These requests came through in a couple of different ways, so I'm going to comment here in a way that may help other projects on CDCgov who may want to use them.

* CoverityScan came through as a "Third-party application request" and since I granted access, now any user should be able to use this within their projects.
* LGTM came through as a github app for specific access to just your two repos. So other projects will need to request specifically for their project. But I'll be able to approve them much more quickly.
* I had already approved SonarCloud 9 days ago, but only for https://github.com/CDCgov/prime-data-input-client. So I don't think I need to do anything here, but let me know if it's not working as you like it. Or if you would also like to use it with  https://github.com/CDCgov/prime-data-hub

By the way, there are currently a few third party applications whitelisted for use on CDCgov:
* <https://scan.coverity.com/>
* <https://slack.com/>
* <https://about.gitlab.com/gitlab-com/>
* <http://www.powerbi.com/>
* <https://developer.github.com/v4/explorer/>
* <https://snyk.io/>

I wish there was a way to approve for only public data access, but, alas, for now they can be authorized to view private data by project admins. The good news is that CDC doesn't actually store any private data in our open source projects.

This is a really helpful issue and I'll eventually work your info from this issue into the [CDC Open Practices Guide](https://github.com/CDCgov/template/blob/master/open_practices.md) to make it easier for other groups to plan and use these tools. If you don't mind, once you get all this stuff running, would you please consider posting a link to your project using them. I think more groups are interested in automated scans but just don't know how yet. There's also an intranet page for scanning techniques if you really want to be helpful and send a PR there, http://it-guides.cdc.gov/source-code/scanningPractices/ [intranet only]
