### ISSUE TITLE
Component Licensing?

### ISSUE THREAD

**Issue by sammysheep** [CDCgov/template#13]
I notice that both Public Domain and Apache 2 are listed in this template. My understanding is that Public Domain is not a license at all and contains no restrictions except perhaps the convention of source attribution. The Apache 2 license is quite permissive but it does have certain restrictions.

My assumptions are:
- If an already licensed component is packaged then that component would be under its existing license. 
- If a component is the partial work of non-CDC folk it may fall under a license depending on what the team decides unless the work is separable between federal and non-federal contributors. Separable work by federal employees should be Public Domain.
- Highly derivative work (simple port or copy) of an existing licensed software will fall under said license.
- If the component is the sole work of a Federal employee, then indeed it is required to be Public Domain.
- Public Domain software can be included in a licensed work BUT I am unfamiliar with any mechanism that would require separable, new contributions from non-federal employees to be dedicated to public domain.
- Modification of public domain code bases likely should be able to retain their status as per the guidance in the template.

I am wondering if the language could be improved to specify how components fall under a license or not (public domain). This may require modules and components be granted separate licensing or public domain dedications, but the package as a whole is generally under the most restrictive license, is it not?

IANAL. Would be grateful for guidance from someone who has more experience in this area.

**Comment by leebrian** [comment]
Thanks for the comment and thinking about this. I want to improve it, but am kind of stuck. The thing about the public domain (and other parts reference cc0) is because that's in there because pretty much everything cdc produces is public domain as a government work. That addresses copyright but isn't a license. So we also specify Apache2 (or MIT, or BSD, or GPL or whatever) to make our work easier for others to use and reduce questions. It also helps with contributions because it can get confusing to contributors who may not understand how to release in public domain but do no how to license their contributions under the particular license.

There was also some thought around while public domain exists, the no warranty notices were useful to explicitly state and reduce confusion by people who might think software does have warranty when it almost never does.

We worked with OGC on this version and the GSA code.gov group and have been stuck at this current version for a few years. I agree I'd like it to be less confusing (and thus more useful and thus more CDC software available) but not sure what action to take as everything got into project specific particulars that didn't generalize into this template.

The current wording applies to the entire project and all components within it but projects can customize if particular parts are under other licenses or restrictions. I feel like there are some examples in CDCGov but couldn't find any to link here. So the entire package would fall under the license unless otherwise stated. Depending on the complexity, it may make it easier to use to just store modules as separate projects that explicitly note their language and then link to them as needed.

If we can come up with specific questions, I can start a new conversation with OGC as they're super smart and have been very helpful with this so far.

**Comment by sammysheep** [comment]
Thanks for the thoughtful response.

I have indeed started borrowing some of the language you all produced and customized it slightly to refer to individual files/scripts rather than the repo as a whole. I dedicate the individual scripts/modules/classes as public domain in the header comments but license the overall project based on component requirements. Some of our components are GPLv3, so the entire package ends up under GPLv3 given the viral license. I note to users that there is additional licensing flexibility for individual files but that the project is generally under license X.

I agree that it makes sense to split up repos with incompatible licensing where the boundaries make sense (software-wise). However, I wouldn't split a project solely for the readability of the license terms. I can provide some more examples when I get further down this road. Most of our software is still on-prem, partially because of the confusion regarding clearance and licensing. The software that has been released pre-dates CDC's expanded use of github and involves explicit naming of component licenses.

Thanks for the distinction between copyright and license, that was a piece I sometimes falsely equivocate.

**Comment by leebrian** [comment]
Glad this is helpful and that's a really good point about GPL licenses. I think the convention is as long as items are clearly marked (in readme or in specific folders) it doesn't really matter to have them in the same repo. I spend a lot of time trying to figure out what clear enough is, and that's where we can loop in OGC to confirm or suggest something. I think the package should be clear so that a user understands whether it's in github, some other site or distribution, or they just find it in a folder.

As you go through these, we could add links to example projects that might be useful references for others.

I'm glad you're building software with this in mind. As I join ID, I'm really interested in how ID packages are used as OSS and we can make them more used in the future.
