### ISSUE TITLE
Fork repo into CDCgov org

### ISSUE THREAD

**Issue by JosiahSiegel** [CDCgov/template#75]
Question from @arnejduranovic

Summary: Fork https://github.com/LinuxForHealth/hl7v2-fhir-converter into CDCgov org

>Does anyone know who has permission to create a repo in the CDCGov organization or how I would go about doing that? We want to fork a public repository... https://github.com/CDCgov. This is the library we want to fork: https://github.com/LinuxForHealth/hl7v2-fhir-converter. We have already done this for https://github.com/HL7/v2-to-fhir but that was Carlos and Patricia

**Comment by leebrian** [comment]
It's the same as creating a new repo. Just open a request for a new repo and put in the notes that you want to fork it from somewhere. I think the link is bit.ly/join_cdcgov but adding @boris-ning-usds in case there's a different form or something. I remember quite a few repos getting on CDCGov this way and you can kind of see based on the fork lineage.

You specify that you want to the be the admin, so that will let you send PRs back to the origin and stuff.
